service: default
env: flex
runtime: nodejs
api_version: '1.0'
threadsafe: true
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.5

network: {}

resources:
  cpu: 1
  memory_gb: 1.75
  disk_size_gb: 10

readiness_check:
  path: /readiness_check
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: /liveness_check
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2